// <auto-generated />
using System;
using IrohBooks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IrohBooks.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260428060347_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IrohBooks.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("IrohBooks.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Technology"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Education"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Biography"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Science"
                        });
                });

            modelBuilder.Entity("IrohBooks.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Name = "Fantasy"
                        },
                        new
                        {
                            GenreId = 2,
                            Name = "Romance"
                        },
                        new
                        {
                            GenreId = 3,
                            Name = "Mystery"
                        },
                        new
                        {
                            GenreId = 4,
                            Name = "Self-Help"
                        },
                        new
                        {
                            GenreId = 5,
                            Name = "Motivation"
                        },
                        new
                        {
                            GenreId = 6,
                            Name = "Programming"
                        },
                        new
                        {
                            GenreId = 7,
                            Name = "Web Development"
                        },
                        new
                        {
                            GenreId = 8,
                            Name = "Data Science"
                        },
                        new
                        {
                            GenreId = 9,
                            Name = "Textbook"
                        },
                        new
                        {
                            GenreId = 10,
                            Name = "Exam Preparation"
                        },
                        new
                        {
                            GenreId = 11,
                            Name = "Autobiography"
                        },
                        new
                        {
                            GenreId = 12,
                            Name = "Memoir"
                        },
                        new
                        {
                            GenreId = 13,
                            Name = "Physics"
                        },
                        new
                        {
                            GenreId = 14,
                            Name = "Biology"
                        },
                        new
                        {
                            GenreId = 15,
                            Name = "Epic Fantasy"
                        },
                        new
                        {
                            GenreId = 16,
                            Name = "Urban Fantasy"
                        },
                        new
                        {
                            GenreId = 17,
                            Name = "Detective"
                        },
                        new
                        {
                            GenreId = 18,
                            Name = "Thriller"
                        },
                        new
                        {
                            GenreId = 19,
                            Name = "Habit Building"
                        },
                        new
                        {
                            GenreId = 20,
                            Name = "Productivity"
                        },
                        new
                        {
                            GenreId = 21,
                            Name = "Coding Practices"
                        },
                        new
                        {
                            GenreId = 22,
                            Name = "System Design"
                        },
                        new
                        {
                            GenreId = 23,
                            Name = "Machine Learning"
                        },
                        new
                        {
                            GenreId = 24,
                            Name = "Algorithm Design"
                        },
                        new
                        {
                            GenreId = 25,
                            Name = "Life Story"
                        },
                        new
                        {
                            GenreId = 26,
                            Name = "Entrepreneur Journey"
                        },
                        new
                        {
                            GenreId = 27,
                            Name = "Cosmology"
                        },
                        new
                        {
                            GenreId = 28,
                            Name = "Astrophysics"
                        },
                        new
                        {
                            GenreId = 29,
                            Name = "Adventure"
                        },
                        new
                        {
                            GenreId = 30,
                            Name = "Philosophical"
                        },
                        new
                        {
                            GenreId = 31,
                            Name = "Career Growth"
                        },
                        new
                        {
                            GenreId = 32,
                            Name = "Best Practices"
                        },
                        new
                        {
                            GenreId = 33,
                            Name = "Problem Solving"
                        },
                        new
                        {
                            GenreId = 34,
                            Name = "Space Science"
                        });
                });

            modelBuilder.Entity("IrohBooks.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("IrohBooks.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("IrohBooks.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "A philosophical novel about following your dreams by Paulo Coelho",
                            Name = "The Alchemist",
                            Price = 500m,
                            Stock = 50
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Description = "A self-improvement book about building good habits by James Clear",
                            Name = "Atomic Habits",
                            Price = 650m,
                            Stock = 40
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Description = "A guide to writing clean and maintainable code by Robert C. Martin",
                            Name = "Clean Code",
                            Price = 800m,
                            Stock = 30
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4,
                            Description = "A comprehensive textbook on algorithms by Thomas H. Cormen",
                            Name = "Introduction to Algorithms",
                            Price = 1200m,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 5,
                            Description = "A biography of Steve Jobs by Walter Isaacson",
                            Name = "Steve Jobs",
                            Price = 700m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 6,
                            Description = "A popular science book on cosmology by Stephen Hawking",
                            Name = "A Brief History of Time",
                            Price = 900m,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            Description = "A fantasy adventure novel by J.R.R. Tolkien",
                            Name = "The Hobbit",
                            Price = 550m,
                            Stock = 35
                        });
                });

            modelBuilder.Entity("IrohBooks.Models.ProductGenre", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("ProductGenres");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            ProductId = 1,
                            GenreId = 2
                        },
                        new
                        {
                            ProductId = 1,
                            GenreId = 29
                        },
                        new
                        {
                            ProductId = 1,
                            GenreId = 30
                        },
                        new
                        {
                            ProductId = 1,
                            GenreId = 16
                        },
                        new
                        {
                            ProductId = 2,
                            GenreId = 4
                        },
                        new
                        {
                            ProductId = 2,
                            GenreId = 5
                        },
                        new
                        {
                            ProductId = 2,
                            GenreId = 19
                        },
                        new
                        {
                            ProductId = 2,
                            GenreId = 20
                        },
                        new
                        {
                            ProductId = 2,
                            GenreId = 31
                        },
                        new
                        {
                            ProductId = 3,
                            GenreId = 6
                        },
                        new
                        {
                            ProductId = 3,
                            GenreId = 7
                        },
                        new
                        {
                            ProductId = 3,
                            GenreId = 21
                        },
                        new
                        {
                            ProductId = 3,
                            GenreId = 18
                        },
                        new
                        {
                            ProductId = 3,
                            GenreId = 33
                        },
                        new
                        {
                            ProductId = 4,
                            GenreId = 9
                        },
                        new
                        {
                            ProductId = 4,
                            GenreId = 10
                        },
                        new
                        {
                            ProductId = 4,
                            GenreId = 24
                        },
                        new
                        {
                            ProductId = 4,
                            GenreId = 33
                        },
                        new
                        {
                            ProductId = 4,
                            GenreId = 22
                        },
                        new
                        {
                            ProductId = 5,
                            GenreId = 11
                        },
                        new
                        {
                            ProductId = 5,
                            GenreId = 12
                        },
                        new
                        {
                            ProductId = 5,
                            GenreId = 25
                        },
                        new
                        {
                            ProductId = 5,
                            GenreId = 26
                        },
                        new
                        {
                            ProductId = 5,
                            GenreId = 31
                        },
                        new
                        {
                            ProductId = 6,
                            GenreId = 13
                        },
                        new
                        {
                            ProductId = 6,
                            GenreId = 27
                        },
                        new
                        {
                            ProductId = 6,
                            GenreId = 28
                        },
                        new
                        {
                            ProductId = 6,
                            GenreId = 34
                        },
                        new
                        {
                            ProductId = 6,
                            GenreId = 30
                        },
                        new
                        {
                            ProductId = 7,
                            GenreId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            GenreId = 15
                        },
                        new
                        {
                            ProductId = 7,
                            GenreId = 29
                        },
                        new
                        {
                            ProductId = 7,
                            GenreId = 3
                        },
                        new
                        {
                            ProductId = 7,
                            GenreId = 17
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IrohBooks.Models.Order", b =>
                {
                    b.HasOne("IrohBooks.Models.ApplicationUser", "User")
                        .WithMany("Order")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IrohBooks.Models.OrderItem", b =>
                {
                    b.HasOne("IrohBooks.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IrohBooks.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IrohBooks.Models.Product", b =>
                {
                    b.HasOne("IrohBooks.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IrohBooks.Models.ProductGenre", b =>
                {
                    b.HasOne("IrohBooks.Models.Genre", "Genre")
                        .WithMany("ProductGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IrohBooks.Models.Product", "Product")
                        .WithMany("ProductGenres")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IrohBooks.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IrohBooks.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IrohBooks.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IrohBooks.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IrohBooks.Models.ApplicationUser", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("IrohBooks.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("IrohBooks.Models.Genre", b =>
                {
                    b.Navigation("ProductGenres");
                });

            modelBuilder.Entity("IrohBooks.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("IrohBooks.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
